name: Deploy to heroku

on:
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Email that you use with heroku
          heroku_email: "schrodinger.hat.show@gmail.com"
          # The appname to use for deploying/updating
          heroku_app_name: "schrodinger-hat-web" #Must be unique in Heroku
          branch: web

